# Generated by Django 3.1.3 on 2020-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0004_auto_20201214_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermaterial',
            name='other_measurement',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='othermaterial',
            name='other_measurement_amount',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
