# Generated by Django 3.1.3 on 2020-12-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0007_auto_20201215_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othermaterial',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='othermaterials', to='workorder_app.workorder'),
        ),
    ]
