# Generated by Django 3.1.3 on 2021-01-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0008_auto_20201217_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='priced',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
