# Generated by Django 3.1.3 on 2021-01-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0009_workorder_priced'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
