# Generated by Django 3.1.3 on 2021-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0010_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='request_for_pricing',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
