# Generated by Django 3.1.3 on 2021-08-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0011_workorder_request_for_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='general_contractor_email',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
