# Generated by Django 3.1.3 on 2021-08-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0012_workorder_general_contractor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_work_performed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='general_contractor_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priced',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='request_for_pricing',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
