# Generated by Django 3.1.3 on 2021-12-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0014_materialproductdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialproductdb',
            name='location',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='materialproductdb',
            name='price',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='materialproductdb',
            name='product_name',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='materialproductdb',
            name='unit_of_measurement',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
