# Generated by Django 3.1.3 on 2021-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0015_auto_20211227_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='None', max_length=300)),
                ('street', models.CharField(default='None', max_length=300)),
                ('city_state_zip', models.CharField(default='None', max_length=300)),
                ('phone_number', models.CharField(default='None', max_length=300)),
                ('email_address', models.CharField(default='None', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
