# Generated by Django 3.1.3 on 2021-12-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0017_ourcompanyinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobname',
            name='gc_city_state_zip',
            field=models.CharField(default='Caldwell, NJ 07000', max_length=255),
        ),
        migrations.AddField(
            model_name='jobname',
            name='gc_phone',
            field=models.CharField(default='123.456.789', max_length=255),
        ),
        migrations.AddField(
            model_name='jobname',
            name='gc_street',
            field=models.CharField(default='111 Roseland Ave', max_length=255),
        ),
    ]
