# Generated by Django 3.1.3 on 2021-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0018_auto_20211228_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice_date',
            field=models.CharField(default='TBD', max_length=255),
        ),
    ]
