# Generated by Django 3.1.3 on 2021-12-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0019_workorder_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='labortype',
            name='total_labor_cost',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='total_material_cost',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='othermaterial',
            name='total_other_material_cost',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
