# Generated by Django 3.1.3 on 2021-12-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0021_auto_20211228_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='total_invoice_amount',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
