# Generated by Django 3.1.3 on 2021-12-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0024_auto_20211228_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='memo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
