# Generated by Django 3.1.3 on 2021-12-29 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0026_remove_workorder_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
