# Generated by Django 3.1.3 on 2021-12-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0027_workorder_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice_number',
            field=models.CharField(default='1111', max_length=255),
        ),
    ]
