# Generated by Django 3.1.3 on 2021-12-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0028_workorder_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='labortype',
            name='hourly_rate',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='per_price',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
