# Generated by Django 3.1.3 on 2022-01-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0029_auto_20211230_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='labortype',
            name='over_hours',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
