# Generated by Django 3.1.3 on 2022-01-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0030_labortype_over_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type_name', models.CharField(default='None', max_length=255)),
                ('job_name', models.CharField(default='None', max_length=255)),
                ('labor_hourly_rate', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
