# Generated by Django 3.1.3 on 2022-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0032_auto_20220120_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='picture_1',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
