# Generated by Django 3.1.3 on 2022-05-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0034_auto_20220502_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborTypeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type_name', models.CharField(default='None', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
